config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  root to: 'home#index'

  devise_for(:user, {
    class_name: 'Spree::User',
    singular: :spree_user,
    controllers: {
      sessions: 'user_sessions',
      registrations: 'user_registrations',
      passwords: 'user_passwords',
      confirmations: 'user_confirmations'
    },
    skip: [:unlocks, :omniauth_callbacks],
    path_names: { sign_out: 'logout' }
  })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  resources :cart_line_items, only: :create

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  resource :checkout_session, only: :new
  resource :checkout_guest_session, only: :create

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkouts#update', as: :update_checkout
  get '/checkout/:state', to: 'checkouts#edit', as: :checkout_state
  get '/checkout', to: 'checkouts#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, except: [:index, :new, :create, :destroy] do
    resources :coupon_codes, only: :create
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/checkouts_controller.rb
# frozen_string_literal: true

# This is somewhat contrary to standard REST convention since there is not
# actually a Checkout object. There's enough distinct logic specific to
# checkout which has nothing to do with updating an order that this approach
# is warranted.
class CheckoutsController < CheckoutBaseController
  before_action :ensure_valid_state
  before_action :check_registration
  before_action :setup_for_current_state

  # Updates the order and advances to the next state (when possible.)
  def update
    if update_order

      assign_temp_address

      unless transition_forward
        redirect_on_failure
        return
      end

      if @order.completed?
        finalize_order
      else
        send_to_next_state
      end

    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def assign_temp_address
    @order.temporary_address = !params[:save_user_address]
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to(checkout_state_path(@order.state))
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
    end
  end

  def finalize_order
    @current_order = nil
    set_successful_flash_notice
    redirect_to completion_route
  end

  def set_successful_flash_notice
    flash.notice = t('spree.order_processed_successfully')
    flash['order_completed'] = true
  end

  def send_to_next_state
    redirect_to checkout_state_path(@order.state)
  end

  def update_params
    case params[:state].to_sym
    when :address
      massaged_params.require(:order).permit(
        permitted_checkout_address_attributes
      )
    when :delivery
      massaged_params.require(:order).permit(
        permitted_checkout_delivery_attributes
      )
    when :payment
      massaged_params.require(:order).permit(
        permitted_checkout_payment_attributes
      )
    else
      massaged_params.fetch(:order, {}).permit(
        permitted_checkout_confirm_attributes
      )
    end
  end

  def massaged_params
    massaged_params = params.deep_dup

    move_payment_source_into_payments_attributes(massaged_params)
    move_wallet_payment_source_id_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)

    massaged_params
  end

  def ensure_valid_state
    unless skip_state_validation?
      if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
         (!params[:state] && !@order.has_checkout_step?(@order.state))
        @order.state = 'cart'
        redirect_to checkout_state_path(@order.checkout_steps.first)
      end
    end

    # Fix for https://github.com/spree/spree/issues/4117
    # If confirmation of payment fails, redirect back to payment screen
    if params[:state] == "confirm" && @order.payment_required? && @order.payments.valid.empty?
      flash.keep
      redirect_to checkout_state_path("payment")
    end
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    # If the user has a default address, the previous method call takes care
    # of setting that; but if he doesn't, we need to build an empty one here
    @order.bill_address ||= Spree::Address.build_default
    @order.ship_address ||= Spree::Address.build_default if @order.checkout_steps.include?('delivery')
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if spree_current_user && spree_current_user.respond_to?(:wallet)
      @wallet_payment_sources = spree_current_user.wallet.wallet_payment_sources
      @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                       @wallet_payment_sources.first
    end
  end

  def order_params
    params.
      fetch(:order, {}).
      permit(:email)
  end

  # HACK: We can't remove `skip_state_validation?` as of now because it is
  # stubbed in some system tests.
  def skip_state_validation?
    false
  end

  # Introduces a registration step whenever the +registration_step+ preference is true.
  def check_registration
    return unless registration_required?

    store_location
    redirect_to new_checkout_session_path
  end

  def registration_required?
    Spree::Auth::Config[:registration_step] &&
      !already_registered?
  end

  def already_registered?
    spree_current_user || guest_authenticated?
  end

  def guest_authenticated?
    current_order&.email.present? &&
      Spree::Config[:allow_guest_checkout]
  end

  # Overrides the equivalent method defined in Spree::Core.  This variation of the method will ensure that users
  # are redirected to the tokenized order url unless authenticated as a registered user.
  def completion_route
    return order_path(@order) if spree_current_user

    token_order_path(@order, @order.guest_token)
  end
end

app/views/checkouts/_checkout_header.html.erb
<header class="checkout-header">
  <h1 class="checkout-header__title">
    <%= t('spree.checkout') %>
  </h1>
  <div class="checkout-header__steps">
    <%= checkout_progress %>
  </div>
</header>

app/views/checkouts/_checkout_step.html.erb
<%= form_for order, url: update_checkout_path(order.state), html: { id: "checkout_form_#{order.state}" } do |form| %>
  <% if order.state == "address" || !order.email? %>
    <div class="text-input">
      <%= form.label :email, 'Customer E-Mail:' %>
      <%= form.email_field :email, required: true, placeholder: 'name@example.com' %>
    </div>
  <% end %>

  <%= render "checkouts/steps/#{order.state}_step", form: form, differentiator: @differentiator %>
<% end %>

app/views/checkouts/_checkout_summary.html.erb
<section class="checkout-summary" id="checkout-summary">
  <h2 class="checkout-summary__title">
    <%= t('spree.order_summary') %>
  </h2>

  <%= render(
    'orders/order_items',
    order: order,
    classes: ['order-items--summary']
  )%>

  <dl>
    <div class="checkout-summary__entry" id="item-total">
      <dt><%= t('spree.item_total') %>:</dt>
      <dd><%= order.display_item_total.to_html %></dd>
    </div>

    <% if order.line_item_adjustments.nonzero.exists? %>
      <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
        <div class="checkout-summary__entry">
          <dt><%= label %></dt>
          <dd><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></dd>
        </div>
      <% end %>
    <% end %>

    <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
      <div class="checkout-summary__entry">
        <dt><%= label %></dt>
        <dd><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></dd>
      </div>
    <% end %>

    <% if order.passed_checkout_step?("delivery") && order.shipments.any? %>
      <div class="checkout-summary__entry">
        <dt><%= t('spree.shipping_total') %>:</dt>
        <dd><%= Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency).to_html %></dd>
      </div>

      <% if order.shipment_adjustments.nonzero.exists? %>
        <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <div class="checkout-summary__entry">
            <dt><%= label %>:</dt>
            <dd><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></dd>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <% if order.adjustments.nonzero.non_tax.eligible.exists? %>
      <div class="checkout-summary__entry" id="summary-order-charges">
        <% order.adjustments.nonzero.non_tax.eligible.each do |adjustment| %>
          <dt><%= adjustment.label %>:</dt>
          <dd><%= adjustment.display_amount.to_html %></dd>
        <% end %>
      </div>
    <% end %>

    <% if order.total_applicable_store_credit > 0.0 %>
      <div class="checkout-summary__entry">
        <dt><%= t('spree.store_credit.store_credit') %>:</dt>
        <dd><%= order.display_total_applicable_store_credit.to_html %></dd>
      </div>
    <% end %>

    <div class="checkout-summary__total">
      <dt><%= t('spree.order_total') %>:</dt>
      <dd><%= order.display_order_total_after_store_credit.to_html %></dd>
    </div>
  </dl>

  <% if order.state == 'payment' %>
    <%= render 'orders/coupon_code' %>
  <% end %>
</section>

app/views/checkouts/_terms_and_conditions.en.html.erb
<p>Put your terms and conditions here</p>

app/views/checkouts/edit.html.erb
<article class="checkout">
  <%= render "shared/error_messages", target: @order %>
  <%= render "checkout_header" %>

  <div class="checkout__main">
    <section class="checkout__step">
      <%= render "checkout_step", order: @order %>
    </section>

    <% if @order.state != "confirm" %>
      <div class="checkout__summary">
        <%= render "checkout_summary", order: @order %>
      </div>
    <% end %>
  </div>
</article>